version: "3.8"

services:
    scrapper:
        build: ./
        container_name: akiya_scrapper
        command: python main.py
        volumes:
        - ./:/usr/src/app/
        - shared_data:/shared
        ports:
        - 5001:5001
        env_file:
        - .env
        depends_on:
        - db

    db:
        image: postgres:14-alpine
        container_name: jp-mart-db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - shared_data:/shared
        env_file: .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DRIVER: ${POSTGRES_DRIVER}
        ports:
            - 5432:5432
        expose:
            - 5432

volumes:
    postgres_data:
    shared_data: