version: "3.8"

services:
    scrapper:
        build: ./
        container_name: akiya_scrapper
        command: /bin/sh -c "python main.py && python ingestion.py && tail -f /dev/null"
        volumes:
        - ./:/usr/src/app/
        - shared_data:/shared
        ports:
        - 5001:5001
        env_file:
        - .env
        depends_on:
        - db
        tty: true
        stdin_open: true
    db:
        image: postgres:14-alpine
        container_name: jp-mart-db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - shared_data:/shared
        env_file: .env
        ports:
            - 5432:5432
        expose:
            - 5432

volumes:
    postgres_data:
    shared_data: