version: "3.8"

services:
    db:
        image: postgres:14-alpine
        container_name: jp-mart-db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: .env
        ports:
            - 5432:5432
        expose:
            - 5432

volumes:
    postgres_data: