version: "3.8"

services:
    scrapper:
        build: ./
        container_name: akiya_scrapper
        command: python main.py
        volumes:
        - ./:/usr/src/app/
        ports:
        - 5001:5001
        env_file:
        - .env
        depends_on:
        - db
    db:
        image: postgres:14-alpine
        container_name: jp-mart-db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: .env
        ports:
            - 5432:5432
        expose:
            - 5432

volumes:
    postgres_data: