from pydantic import BaseModel
from decouple import config
from typing import List


class JapanLocation(BaseModel):
    name: str
    num: int = 100


class AkiyaConfig(BaseModel):
    aws_access_key_id: str
    aws_secret_access_key: str
    aws_default_region: str
    bucket: str
    last_page: int
    chunk_size: int
    secret: str
    listing_attributes: List[str]
    listings_attributes: List[str]
    coordinate_attributes: List[str]
    cities: List[JapanLocation]
    email: str
    password: str


JAPAN_CITIES = [
    JapanLocation(name="Tokyo", num=200),
    JapanLocation(name="Yokohama", num=150),
    JapanLocation(name="Osaka", num=150),
    JapanLocation(name="Nagoya", num=120),
    JapanLocation(name="Sapporo", num=120),
    JapanLocation(name="Kobe", num=120),
    JapanLocation(name="Fukuoka", num=120),
    JapanLocation(name="Kyoto", num=200),
    JapanLocation(name="Kawasaki", num=100),
    JapanLocation(name="Saitama", num=100),
    JapanLocation(name="Hiroshima", num=150),
    JapanLocation(name="Sendai", num=100),
    JapanLocation(name="Kitakyushu", num=100),
    JapanLocation(name="Chiba", num=100),
    JapanLocation(name="Setagaya", num=100),
    JapanLocation(name="Sakai", num=100),
    JapanLocation(name="Niigata", num=100),
    JapanLocation(name="Hamamatsu", num=100),
    JapanLocation(name="Kumamoto", num=100),
    JapanLocation(name="Sagamihara", num=100),
    JapanLocation(name="Nerima", num=100),
    JapanLocation(name="Shizuoka", num=100),
    JapanLocation(name="Okayama", num=100),
    JapanLocation(name="Kagoshima", num=100),
    JapanLocation(name="Funabashi", num=100),
    JapanLocation(name="Higashi-Osaka", num=100),
    JapanLocation(name="Amagasaki", num=100),
    JapanLocation(name="Hachioji", num=100),
    JapanLocation(name="Matsudo", num=100),
    JapanLocation(name="Himeji", num=100),
    JapanLocation(name="Nagasaki", num=100),
    JapanLocation(name="Matsuyama", num=100),
    JapanLocation(name="Kanazawa", num=100),
    JapanLocation(name="Kawaguchi", num=100),
    JapanLocation(name="Ichikawa", num=100),
    JapanLocation(name="Yokosuka", num=100),
    JapanLocation(name="Nishinomiya", num=100),
    JapanLocation(name="Utsunomiya", num=100),
    JapanLocation(name="Urawa", num=100),
    JapanLocation(name="Kurashiki", num=100),
    JapanLocation(name="Gifu", num=100),
    JapanLocation(name="Toyonaka", num=100),
    JapanLocation(name="Oita", num=100),
    JapanLocation(name="Omiya", num=100),
    JapanLocation(name="Wakayama", num=100),
    JapanLocation(name="Hirakata", num=100),
    JapanLocation(name="Fukuyama", num=100),
    JapanLocation(name="Takatsuki", num=100),
    JapanLocation(name="Asahikawa", num=100),
    JapanLocation(name="Iwaki", num=100),
    JapanLocation(name="Fujisawa", num=100),
    JapanLocation(name="Nara", num=100),
    JapanLocation(name="Machida", num=100),
    JapanLocation(name="Nagano", num=100),
    JapanLocation(name="Suita", num=100),
    JapanLocation(name="Toyohashi", num=100),
    JapanLocation(name="Toyota", num=100),
    JapanLocation(name="Takamatsu", num=100),
    JapanLocation(name="Toyama", num=100),
    JapanLocation(name="Kochi", num=100),
    JapanLocation(name="Koriyama", num=100),
    JapanLocation(name="Hakodate", num=100),
    JapanLocation(name="Okazaki", num=100),
    JapanLocation(name="Kashiwa", num=100),
    JapanLocation(name="Kawagoe", num=100),
    JapanLocation(name="Naha", num=100),
    JapanLocation(name="Tokorozawa", num=100),
    JapanLocation(name="Akita", num=100),
    JapanLocation(name="Aomori", num=100),
    JapanLocation(name="Miyazaki", num=100),
    JapanLocation(name="Maebashi", num=100),
    JapanLocation(name="Koshigaya", num=100),
    JapanLocation(name="Yao", num=100),
    JapanLocation(name="Fukushima", num=100),
    JapanLocation(name="Yokkaichi", num=100),
    JapanLocation(name="Akashi", num=100),
    JapanLocation(name="Kasugai", num=100),
    JapanLocation(name="Tokushima", num=100),
    JapanLocation(name="Shimonoseki", num=100),
    JapanLocation(name="Ichinomiya", num=100),
    JapanLocation(name="Otsu", num=100),
    JapanLocation(name="Ichihara", num=100),
    JapanLocation(name="Neyagawa", num=100),
    JapanLocation(name="Ibaraki", num=100),
    JapanLocation(name="Fukui", num=100),
    JapanLocation(name="Yamagata", num=100),
    JapanLocation(name="Hiratsuka", num=100),
    JapanLocation(name="Sasebo", num=100),
    JapanLocation(name="Shimizu", num=100),
    JapanLocation(name="Hachinohe", num=100),
    JapanLocation(name="Kakogawa", num=100),
    JapanLocation(name="Takasaki", num=100),
    JapanLocation(name="Morioka", num=100),
    JapanLocation(name="Mito", num=100),
    JapanLocation(name="Kurume", num=100),
    JapanLocation(name="Fuji", num=100),
    JapanLocation(name="Kure", num=100),
    JapanLocation(name="Numazu", num=100),
    JapanLocation(name="Fuchu", num=100),
    JapanLocation(name="Soka", num=100),
    JapanLocation(name="Kushiro", num=100),
    JapanLocation(name="Hitachi", num=100),
    JapanLocation(name="Takarazuka", num=100),
]

LISTINGS_ATTRIBUTES = [
    "construction_year",
    "gross_yield",
    "image_urls",
    "is_featured",
    "is_liked",
    "kind",
    "lat",
    "like_count",
    "listing_id",
    "lon",
    "prefecture",
    "price_foreign",
    "price_yen",
    "translated_address",
    "view_count",
]
LISTING_ATTRIBUTES = [
    "address",
    "building_area",
    "construction_year",
    "description",
    "first_seen_at",
    "gross_yield",
    "has_free_parking",
    "image_urls",
    "is_condo",
    "is_geocoded",
    "is_hidden",
    "is_liked",
    "is_toushi",
    "land_area",
    "last_seen_at",
    "lat",
    "like_count",
    "listing_id",
    "llm_area",
    "llm_description",
    "lon",
    "management_fee_foreign",
    "management_fee_yen",
    "needs_update",
    "prefecture",
    "price_foreign",
    "price_yen",
    "remarks",
    "repair_fee_foreign",
    "repair_fee_yen",
    "station_distance",
    "station_lat",
    "station_lon",
    "station_name",
    "translated_address",
    "translated_condition",
    "translated_description",
    "translated_remarks",
    "url",
]
COORDIATE_ATTRIBUTES = ["sw_lon", "sw_lat", "ne_lon", "ne_lat", "city"]
akiya_config = AkiyaConfig(
    aws_access_key_id=config("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=config("AWS_SECRET_ACCESS_KEY"),
    aws_default_region=config("AWS_DEFAULT_REGION"),
    bucket=config("BUCKET"),
    last_page=config("LAST_PAGE"),
    chunk_size=config("CHUNK_SIZE"),
    secret=config("SECRET_KEY"),
    listing_attributes=LISTING_ATTRIBUTES,
    listings_attributes=LISTINGS_ATTRIBUTES,
    coordinate_attributes=COORDIATE_ATTRIBUTES,
    cities=JAPAN_CITIES,
    email=config("EMAIL"),
    password=config("PASSWORD"),
)
