from pydantic import BaseModel
from decouple import config
from typing import List


class AkiyaConfig(BaseModel):
    aws_access_key_id: str
    aws_secret_access_key: str
    aws_default_region: str
    bucket: str
    last_page: int
    chunk_size: int
    secret: str
    listing_attributes: List[str]
    listings_attributes: List[str]
    coordinate_attributes: List[str]
    cities: List[str]
    email: str
    password: str


JAPAN_CITIES = [
    "Tokyo",
    "Yokohama",
    # "Osaka",
    # "Nagoya",
    # "Sapporo",
    # "Kobe",
    # "Fukuoka",
    # "Kyoto",
    # "Kawasaki",
    # "Saitama",
    # "Hiroshima",
    # "Sendai",
    # "Kitakyushu",
    # "Chiba",
    # "Setagaya",
    # "Sakai",
    # "Niigata",
    # "Hamamatsu",
    # "Kumamoto",
    # "Sagamihara",
    # "Nerima",
    # "Shizuoka",
    # "Okayama",
    # "Kagoshima",
    # "Funabashi",
    # "Higashi-Osaka",
    # "Amagasaki",
    # "Hachioji",
    # "Matsudo",
    # "Himeji",
    # "Nagasaki",
    # "Matsuyama",
    # "Kanazawa",
    # "Kawaguchi",
    # "Ichikawa",
    # "Yokosuka",
    # "Nishinomiya",
    # "Utsunomiya",
    # "Urawa",
    # "Kurashiki",
    # "Gifu",
    # "Toyonaka",
    # "Oita",
    # "Omiya",
    # "Wakayama",
    # "Hirakata",
    # "Fukuyama",
    # "Takatsuki",
    # "Asahikawa",
    # "Iwaki",
    # "Fujisawa",
    # "Nara",
    # "Machida",
    # "Nagano",
    # "Suita",
    # "Toyohashi",
    # "Toyota",
    # "Takamatsu",
    # "Toyama",
    # "Kochi",
    # "Koriyama",
    # "Hakodate",
    # "Okazaki",
    # "Kashiwa",
    # "Kawagoe",
    # "Naha",
    # "Tokorozawa",
    # "Akita",
    # "Aomori",
    # "Miyazaki",
    # "Maebashi",
    # "Koshigaya",
    # "Yao",
    # "Fukushima",
    # "Yokkaichi",
    # "Akashi",
    # "Kasugai",
    # "Tokushima",
    # "Shimonoseki",
    # "Ichinomiya",
    # "Otsu",
    # "Ichihara",
    # "Neyagawa",
    # "Ibaraki",
    # "Fukui",
    # "Yamagata",
    # "Hiratsuka",
    # "Sasebo",
    # "Shimizu",
    # "Hachinohe",
    # "Kakogawa",
    # "Takasaki",
    # "Morioka",
    # "Mito",
    # "Kurume",
    # "Fuji",
    # "Kure",
    # "Numazu",
    # "Fuchu",
    # "Soka",
    # "Kushiro",
    # "Hitachi",
    # "Takarazuka",
]
LISTINGS_ATTRIBUTES = [
    "construction_year",
    "gross_yield",
    "image_urls",
    "is_featured",
    "is_liked",
    "kind",
    "lat",
    "like_count",
    "listing_id",
    "lon",
    "prefecture",
    "price_foreign",
    "price_yen",
    "translated_address",
    "view_count",
]
LISTING_ATTRIBUTES = [
    "address",
    "building_area",
    "construction_year",
    "description",
    "first_seen_at",
    "gross_yield",
    "has_free_parking",
    "image_urls",
    "is_condo",
    "is_geocoded",
    "is_hidden",
    "is_liked",
    "is_toushi",
    "land_area",
    "last_seen_at",
    "lat",
    "like_count",
    "listing_id",
    "llm_area",
    "llm_description",
    "lon",
    "management_fee_foreign",
    "management_fee_yen",
    "needs_update",
    "prefecture",
    "price_foreign",
    "price_yen",
    "remarks",
    "repair_fee_foreign",
    "repair_fee_yen",
    "station_distance",
    "station_lat",
    "station_lon",
    "station_name",
    "translated_address",
    "translated_condition",
    "translated_description",
    "translated_remarks",
    "url",
]
COORDIATE_ATTRIBUTES = ["sw_lon", "sw_lat", "ne_lon", "ne_lat", "city"]
akiya_config = AkiyaConfig(
    aws_access_key_id=config("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=config("AWS_SECRET_ACCESS_KEY"),
    aws_default_region=config("AWS_DEFAULT_REGION"),
    bucket=config("BUCKET"),
    last_page=config("LAST_PAGE"),
    chunk_size=config("CHUNK_SIZE"),
    secret=config("SECRET_KEY"),
    listing_attributes=LISTING_ATTRIBUTES,
    listings_attributes=LISTINGS_ATTRIBUTES,
    coordinate_attributes=COORDIATE_ATTRIBUTES,
    cities=JAPAN_CITIES,
    email=config("EMAIL"),
    password=config("PASSWORD"),
)
